# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
#flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# target 'Vstagram' do
#   config = use_native_modules!
#   use_frameworks! :linkage => :static
#   use_react_native!(
#     :path => config[:reactNativePath],
#     :flipper_configuration => flipper_config,
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )
#
#   target 'VstagramTests' do
#     inherit! :complete
#     # Pods for testing
#   end
# end
#
# target 'OneSignalNotificationServiceExtension' do
# use_frameworks! :linkage => :static
#   pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
# end
target 'Vstagram' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'VstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# target 'OneSignalNotificationServiceExtension' do
#   use_frameworks! :linkage => :static
#   pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
# end

#
# target 'videoplayer' do
#   config = use_native_modules!
#   use_frameworks! :linkage => :static
#
#   if ENV['RNV_SAMPLE_ENABLE_ADS']
#     $RNVideoUseGoogleIMA = true
#   end
#   if ENV['RNV_SAMPLE_VIDEO_CACHING']
#     $RNVideoUseVideoCaching = true
#   end
#
#   # Flags change depending on the env values.
#   flags = get_default_flags()
#
#   use_react_native!(
#     :path => config[:reactNativePath],
#     # Hermes is now enabled by default. Disable by setting this flag to false.
#     :hermes_enabled => flags[:hermes_enabled],
#     :fabric_enabled => flags[:fabric_enabled],
#     # Enables Flipper.
#     #
#     # Note that if you have use_frameworks! enabled, Flipper will not work and
#     # you should disable the next line.
#     # :flipper_configuration => flipper_config,
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )
#
#   target 'videoplayerTests' do
#     inherit! :complete
#     # Pods for testing
#   end
# end

post_install do |installer|
  targets = installer.pods_project.targets
  react_native_post_install(
    installer,
    use_native_modules![:reactNativePath],
    :mac_catalyst_enabled => false
  )
end
